{% set version = "1.0.0" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/InfOmics/CRISPRitz/archive/master.tar.gz
  sha256: c99307ebd756c26495dccd2ad32f6fc61816428e555d7ee5e11394adab7278c9

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{compiler('cxx')}} =5.4
    - make
    - boost
    
  host:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    
  run:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/InfOmics/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
