{% set version = "1.0.7" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/InfOmics/CRISPRitz/archive/master.tar.gz 

build:
  number: 1

requirements:
  build:
    - {{compiler('cxx')}} =5.4 # [not osx]
    - {{compiler('cxx')}} # [osx]
    - make
    - boost
    - openmp
    
  host:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    
  run:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/InfOmics/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
  