{% set version = "1.0.8" %}

package:
  name: crispritz
  version: {{ version }}

source:
  url: https://github.com/InfOmics/CRISPRitz/archive/v{{ version }}.tar.gz
  sha256: cc3268c002625bc5169dfb6bf39c9e0400a993d7a3d591fd9faeedfb7424baf3

build:
  number: 0

requirements:
  build:
    - {{compiler('cxx')}} =5.4 # [not osx]
    - {{compiler('cxx')}} # [osx]
    - make
    - boost
    - openmp
    
  host:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    
  run:
    - intervaltree
    - matplotlib
    - pandas
    - scipy
    - numpy
    - more-itertools
    - statsmodels
    - bcftools
    - boost
    - tk
    - openmp
    
test:
  commands:
    - crispritz.py

about:
  home: https://github.com/InfOmics/CRISPRitz
  license: GPL3
  summary: CRISPRitz, tool package for CRISPR experiments assessment and analysis.
